$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: used_cars_training_pipeline
experiment_name: used-cars-price-prediction
description: End-to-end pipeline (prep -> train -> register) for used car price prediction

# -------- Pipeline Inputs --------
inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data@latest   # OR point to repo file using local path (see note below)
  test_train_ratio:
    type: number
    default: 0.2

# -------- Pipeline Outputs --------
outputs:
  model_info_output_path:

# -------- Settings --------
settings:
  default_compute: azureml:cpu-cluster

jobs:
  prep_data:
    type: command
    display_name: prep_data
    code: ./../../../data/used_cars.csv
    environment: azureml:used-cars-train-env@latest
    command: >-
      python prep.py
      --data ${{inputs.raw_data}}
      --test_train_ratio ${{inputs.test_train_ratio}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
      test_train_ratio: ${{parent.inputs.test_train_ratio}}
    outputs:
      train_data:
        type: uri_folder
      test_data:
        type: uri_folder

  train_model:
    type: command
    display_name: train_model
    code: ../../../data-science/src
    environment: azureml:used-cars-train-env@latest
    command: >-
      python train.py
      --train_data ${{inputs.train_data}}
      --test_data ${{inputs.test_data}}
      --model_output ${{outputs.model_output}}
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: uri_folder

  register_model:
    type: command
    display_name: register_model
    code: ../../../data-science/src
    environment: azureml:used-cars-train-env@latest
    command: >-
      python register.py
      --model_path ${{inputs.model_path}}
      --model_name used_cars_price_model
      --model_info_output_path ${{outputs.model_info_output_path}}
    inputs:
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}