$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: used-cars-training-pipeline
experiment_name: used-cars-price-prediction
description: Training Pipeline to predict used car prices using RandomTreeRegressor

inputs:
  input:
    type: uri_file
    path: azureml:used-cars-data@latest

outputs:
  train_data:
  test_data:
  model_info_output_path:

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:test-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    type: command
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      python prep.py
      --raw_data ${{inputs.raw_data}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.input}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    type: sweep
    name: sweep_job
    display_name: sweep-job
    compute: azureml:test-cluster
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial:
      type: command
      code: ../../../data-science/src
      command: >-
        python train.py
        --train_data ${{inputs.train_data}}
        --test_data ${{inputs.test_data}}
        --n_estimators ${{inputs.n_estimators}}
        --max_depth ${{inputs.max_depth}}
        --model_output ${{outputs.model_output}}
      environment: azureml:used-cars-train-env@latest
      inputs:
        train_data: ${{parent.inputs.train_data}}
        test_data: ${{parent.inputs.test_data}}
        n_estimators:
          type: integer
        max_depth:
          type: integer
      outputs:
        model_output:
          type: mlflow_model
    search_space:
      n_estimators:
        type: choice
        values: [50, 100, 200, 400]
      max_depth:
        type: choice
        values: [5, 10, 20, 30]
    objective:
      goal: minimize
      primary_metric: rmse
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    type: command
    name: register_model
    display_name: register-model
    code: ../../../data-science/src
    command: >-
      python register.py
      --model_name "${{inputs.model_name}}"
      --model_path "${{inputs.model_path}}"
      --model_info_output_path "${{outputs.model_info_output_path}}"
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used-cars-random-tree-model"
      model_path:
        type: mlflow_model
        path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
