$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: used_cars_train_rf
display_name: Train Used Cars RandomForest Regressor
type: command

inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: integer
    default: 200
  max_depth:
    type: integer
    default: 10

outputs:
  model_output:
    type: mlflow_model

code: ../../../data-science/src

environment: azureml:used-cars-train-env@latest

command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}