$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command
name: used-cars-random-tree-train
display_name: used-cars-random-tree-train
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: integer
    default: 200
  max_depth:
    type: integer
    default: 10
outputs:
  model_output:
    # FIXED: explicit mode so AzureML mounts the output directory correctly
    type: mlflow_model
code: ../../../data-science/src
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}
# FIXED: must match the environment name registered by register-environment job
environment: azureml:used-cars-train-env@latest
