$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: used-cars-train-env
description: Environment for used cars price prediction training (sklearn + mlflow)
conda_file: ../../../data-science/environment/train-conda.yml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04