$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command
name: train_used_cars_model
display_name: train_used_cars_model

inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder

outputs:
  model_output:
    type: mlflow_model

code: ../../../data-science/src

command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --model_output ${{outputs.model_output}}

environment: azureml:used-cars-train-env@latest