channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  # FIXED: Python 3.7.5 is EOL; 3.8 is the minimum supported by AzureML openmpi images
  # and required by scikit-learn >= 1.0
  - python=3.8
  - pip
  - pip:
      # FIXED: updated to compatible, non-EOL package versions
      - azureml-mlflow==1.51.0
      - azure-ai-ml==1.12.0
      - pyarrow==12.0.0
      - scikit-learn==1.3.0
      - pandas==1.5.3
      - numpy==1.24.3
      - joblib==1.3.2
      - matplotlib==3.7.2
      - mlflow==2.8.1
